#ifndef __DEF_H_
#define __DEF_H_

#define STRING_PRINT_S 
#define STRING_LENGTH_S
#define STRING_COPY_S
#define STRING_REVERSE_S
#define STRING_COMPARE_S
#define STRING_CONCATENATE_S
#define STRING_VOWEL_S
#define STRING_VOWEL_CHECK_S
#define CHAR_VOWEL_CHECK_S
#define CHAR_SWAP_S
#define STRING_VOWEL_REMOVE_1_S
#define STRING_VOWEL_REMOVE_2_S
#define STRING_PALINDROME_S
#define STRING_ALPHA_ORDER_SORT_S
#define STRING_REMOVE_EXPECT_CHAR_S
#define STRING_REMOVE_SPACES_S
#define STRING_USER_DATA_CHECK
#define STRING_MATCH_S

#endif
