# Project: Basic_String_Operation
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o string_s.o
LINKOBJ  = main.o string_s.o
LIBS     = -L"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/lib" -L"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/include" -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/include" -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/SIVAPRAVEEN_DEVC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Basic_String_Operation.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

string_s.o: string_s.c
	$(CC) -c string_s.c -o string_s.o $(CFLAGS)
